title: El Arkhe
description: Talleres en análisis multi-ómico y exploración científico–cultural.
theme: just-the-docs

url: "https://el-arkhe.github.io"

search_enabled: true
nav_sort: case_insensitive
